port: 7882
bind_addresses:
  - "0.0.0.0"
rtc:
  tcp_port: 7883
  port_range_start: 50200
  port_range_end: 60000
  use_external_ip: true
  node_ip: <SERVER_IP>
keys:
  devkey: secret
logging:
  level: info
webhook:
  api_key: devkey
room:
  auto_create: true
  empty_timeout: 300
  max_participants: 100
redis:
  address: "127.0.0.1:6379"
ingress:
  rtmp_base_url: "rtmp://127.0.0.1:1935/live"