/**
 * StreamHandler sub-module: graceful-degradation test stream.
 *
 * Registers `request-test-stream` — the viewer-side graceful-degradation
 * request (emitted by the client's StreamSwitchManager fallback chain). Starts
 * the legacy TestStreamService client-side pattern and emits
 * `test-stream-available`, which is exactly the event the client waits on.
 *
 * The prior ViewbotService auto-start branch was removed with the ViewbotService
 * creation half: under LiveKit, viewbots are never started via
 * ViewbotService.startViewbot (they run through SimpleViewBotRotation →
 * ViewBotLiveKitService), and that branch emitted `new-streamer`/`viewbot-
 * available` — events the fallback client never listened for — so it could not
 * complete the switch. TestStreamService is the only path that satisfies the
 * client contract.
 *
 * Takes the same `(io, socket, deps)`.
 */
const logger = require('../../bootstrap/logger').child({ svc: 'StreamHandler' });

module.exports = function registerTestStream(io, socket, deps) {
  const {
    streamService,
    testStreamService,
  } = deps;

  // Handle graceful degradation test stream request
  socket.on('request-test-stream', async () => {
    logger.info(`🧪 GRACEFUL DEGRADATION: Test stream requested by ${socket.id}`);

    const testStreamStatus = testStreamService.getTestStreamStatus();

    if (!testStreamStatus.isActive) {
      const result = testStreamService.startTestStream({
        autoGenerated: true,
        reason: 'graceful_degradation_fallback'
      });

      if (result.success) {
        streamService.setStreamer(result.streamId, 'test');
        logger.info('🧪 GRACEFUL DEGRADATION: Auto-started test stream for fallback');
        io.emit('test-stream-available', { streamId: result.streamId });
      }
    } else {
      socket.emit('test-stream-available', { streamId: testStreamStatus.streamId });
    }
  });
};
