/**
 * StreamHandler sub-module: graceful-degradation test stream.
 *
 * Registers `request-test-stream` — viewer-side graceful-degradation request.
 * If no ViewbotService is wired, falls back to the legacy TestStreamService.
 * Otherwise auto-starts a ViewBot with synthetic-user-id linkage so the buff
 * system treats it as a streamer. Broadcasts new-streamer + bumps the viewer
 * count.
 *
 * Handler body is VERBATIM from the original StreamHandler.js; this is a pure
 * extraction with no logic change. Takes the same `(io, socket, deps)`.
 */
const logger = require('../../bootstrap/logger').child({ svc: 'StreamHandler' });

module.exports = function registerTestStream(io, socket, deps) {
  const {
    streamService,
    sessionService,
    testStreamService,
    getViewbotService,
    broadcastGlobalCooldown,
    viewerCountNotifier,
  } = deps;

  // Handle graceful degradation viewbot stream request
  socket.on('request-test-stream', async () => {
    logger.info(`🧪 GRACEFUL DEGRADATION: Viewbot stream requested by ${socket.id}`);

    // Late-init service resolution: viewbotService can flip from null to a
    // real instance after MediaSoup init lands. Capture once per request so
    // the branch below sees a consistent value.
    const viewbotService = getViewbotService();

    if (!viewbotService) {
      logger.info('⚠️ GRACEFUL DEGRADATION: ViewbotService not available, falling back to test stream');

      // Fallback to legacy test stream
      const testStreamStatus = testStreamService.getTestStreamStatus();

      if (!testStreamStatus.isActive) {
        const result = testStreamService.startTestStream({
          autoGenerated: true,
          reason: 'graceful_degradation_fallback'
        });

        if (result.success) {
          streamService.setStreamer(result.streamId, 'test');
          logger.info('🧪 GRACEFUL DEGRADATION: Auto-started test stream for fallback');
          io.emit('test-stream-available', { streamId: result.streamId });
        }
      } else {
        socket.emit('test-stream-available', { streamId: testStreamStatus.streamId });
      }
      return;
    }

    // Check if viewbot is available or start one
    const viewbotStatus = viewbotService.getViewbotStatus();

    if (!viewbotStatus.isActive) {
      // Start viewbot automatically for fallback
      const result = await viewbotService.startViewbot({
        config: {
          content: 'clock',
          type: 'viewbot'
        },
        autoGenerated: true,
        reason: 'graceful_degradation_fallback'
      });

      if (result.success) {
        streamService.setStreamer(result.streamId, 'viewbot');
        logger.info('🤖 GRACEFUL DEGRADATION: Auto-started viewbot for fallback');

        // Create synthetic user ID for viewbot to enable buff/debuff support
        const syntheticUserId = -Math.abs(result.streamId.hashCode ? result.streamId.hashCode() : result.streamId.split('-')[1].slice(0, 8).split('').reduce((a, b) => (a * 31 + b.charCodeAt(0)) & 0x7fffffff, 0));
        logger.info(`🎭 BUFF: Created synthetic user ID ${syntheticUserId} for auto-started viewbot ${result.streamId}`);

        // Link synthetic user ID to viewbot socket ID for buff system compatibility
        sessionService.linkUserToSocket(result.streamId, syntheticUserId);
        logger.info(`🎭 BUFF: Linked auto-started viewbot ${result.streamId} to synthetic user ${syntheticUserId} for buff system`);

        // Broadcast global cooldown to all users
        await broadcastGlobalCooldown(result.streamId);

        // Notify all viewers about viewbot availability
        io.emit('new-streamer', {
          streamerId: result.streamId,
          newStreamId: result.streamId,
          isViewbot: true,
          hasRealStream: true,
          streamType: 'viewbot'
        });
        viewerCountNotifier.broadcast();
      }
    } else {
      // Viewbot already active, just notify
      socket.emit('viewbot-available', { streamId: viewbotStatus.streamId });
    }
  });
};
